version: "1"

services:
  - type: web
    name: sevens-cars-system
    env: python
    plan: free
    region: oregon
    buildCommand: |
      apt-get update -y
      apt-get install -y python3.11 python3.11-venv python3.11-distutils
      ln -sf /usr/bin/python3.11 /usr/bin/python3
      cd 7scars
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: |
      cd 7scars
      . venv/bin/activate
      gunicorn app:app
